baseURL = "/"
languageCode = "pt-br"
title = "Dev Files"
theme = "tale"
googleAnalitycs = "UA-141576028-1"
disqusShortname = "alemos_83"
preserveTaxonomyNames = true
enableEmoji = true

[Author]
  name="Dev Files"

  