baseURL = "/"
languageCode = "pt-br"
title = "Dev Files"
theme = "tale"
googleAnalytics = "UA-141576028-1"
disqusShortname = "alemos-dev"
preserveTaxonomyNames = true
enableEmoji = true

[Author]
  name="Dev Files"

[taxonomies]
  category = "categorias"
 